quiltt/quiltt-js

.changeset/nervous-moose-tan.md
ECMAScript/react/package.json
ECMAScript/react/src/hooks/useQuilttConnector.ts
pnpm-lock.yaml

- Add react and react-dom as dev dependency
- Add `useQuilttConnector` to list of side effects

Add react and react-dom as dev dependency

---

.changeset/light-mirrors-bake.md
.github/workflows/release.yml
.npmrc
ECMAScript/core/.npmrc
ECMAScript/core/package.json
ECMAScript/react/package.json
package.json

Closes https://github.com/quiltt/quiltt-public/issues/71

Publish to npm registry

---

.changeset/spotty-deers-try.md

Prepare release

---

.changeset/serious-maps-move.md
.github/workflows/ci.yml
ECMAScript/react/README.md
ECMAScript/react/src/components/QuilttButton.tsx
ECMAScript/react/src/components/QuilttContainer.tsx
ECMAScript/react/src/components/index.ts
ECMAScript/react/src/hooks/useQuilttConnector.ts
ECMAScript/react/src/index.ts
ECMAScript/react/test-apps/nextjs/.gitignore
ECMAScript/react/test-apps/nextjs/app/components/TestCustomLauncher.cy.tsx
ECMAScript/react/test-apps/nextjs/app/components/TestCustomLauncher.tsx
ECMAScript/react/test-apps/nextjs/app/components/TestQuilttButton.cy.tsx
ECMAScript/react/test-apps/nextjs/app/components/TestQuilttButton.tsx
ECMAScript/react/test-apps/nextjs/app/components/TestQuilttContainer.cy.tsx
ECMAScript/react/test-apps/nextjs/app/components/TestQuilttContainer.tsx
ECMAScript/react/test-apps/nextjs/app/components/index.ts
ECMAScript/react/test-apps/nextjs/app/page.tsx
ECMAScript/react/test-apps/nextjs/cypress.config.ts
ECMAScript/react/test-apps/nextjs/cypress/fixtures/example.json
ECMAScript/react/test-apps/nextjs/cypress/support/commands.ts
ECMAScript/react/test-apps/nextjs/cypress/support/component-index.html
ECMAScript/react/test-apps/nextjs/cypress/support/component.ts
ECMAScript/react/test-apps/nextjs/package.json
package.json
pnpm-lock.yaml
turbo.json

Create new React Connector SDK helper components supported by refactored hook.
Not sure the best way to test this; but unless React does something dirty to my attributes I think this should work.
Depends on: https://github.com/quiltt/quiltt/pull/5470

Create new React Connector SDK

---

ECMAScript/core/README.md
ECMAScript/core/package.json
ECMAScript/react/README.md
ECMAScript/react/package.json

- Closes #94 
- Add npm + CI tags to READMEs

Update React package README for v2

---

.changeset/heavy-mirrors-dress.md
ECMAScript/core/package.json
ECMAScript/core/src/api/graphql/links/AuthLink.ts
ECMAScript/react/README.md
ECMAScript/react/package.json
ECMAScript/react/src/providers/QuilttAuthProvider.tsx

- Fix `useQuilttConnector` example
- Add npm keywords + correct homepage
- Add changeset since v2.1

Prepare for v2.1.1 release

---

.changeset/khaki-clouds-raise.md
ECMAScript/react/src/hooks/useSession.ts
ECMAScript/react/test-apps/nextjs/package.json
pnpm-lock.yaml

This supports using the hook with multiple session types

Add support for customizing the session storage key in `useSession`

---

.changeset/plenty-trains-exist.md
ECMAScript/react/src/hooks/session/useImportSession.ts
ECMAScript/react/src/hooks/useQuilttSession.ts

- Add ability for session import to validate environment

Add ability for session import to validate environment

---

.changeset/big-comics-travel.md
ECMAScript/core/src/api/browser.ts
ECMAScript/react/src/components/QuilttButton.tsx
ECMAScript/react/src/components/QuilttContainer.tsx

Improve sdk type namespacing

---

ECMAScript/react-native/README.md
ECMAScript/react-native/example/App.tsx
ECMAScript/react-native/example/metro.config.js
ECMAScript/react-native/example/package.json
ECMAScript/react-native/example/yarn.lock
README.md

Confirmed released version of react native package is working in example app.
And some quick README fix

Quick README fix

---

.changeset/nice-crabs-drum.md
ECMAScript/core/src/api/browser.ts

Add profileId to ConnectorSDKCallbackMetadata

Add profileId to ConnectorSDKCallbackMetadata

---

.changeset/ninety-queens-repeat.md
ECMAScript/react-native/README.md
ECMAScript/react-native/example/package.json
ECMAScript/react-native/example/screens/ConnectorScreen.tsx
ECMAScript/react-native/example/yarn.lock
ECMAScript/react-native/package.json
ECMAScript/react-native/src/components/QuilttConnector.tsx
pnpm-lock.yaml

Closes: https://github.com/quiltt/quiltt-public/issues/149

Fix MX Oauth and move some lib into peer dependencies

---

.changeset/proud-kings-lick.md
ECMAScript/core/src/api/graphql/links/RetryLink.ts

See: https://quiltt.slack.com/archives/C05VDNKNREW/p1703127562036849

Retry GraphQL errors on network errors

---

.changeset/serious-donkeys-clean.md
ECMAScript/react-native/README.md
ECMAScript/react-native/declarations.d.ts
ECMAScript/react-native/example/package.json
ECMAScript/react-native/example/yarn.lock
ECMAScript/react-native/package.json
ECMAScript/react-native/src/components/QuilttConnector.tsx
ECMAScript/react-native/src/index.ts
ECMAScript/react-native/tsconfig.json
pnpm-lock.yaml

Closes: #176 
* Not using corejs because some babel stuff might mess things up

Fix URL and atob polyfill

---

.changeset/perfect-readers-look.md
ECMAScript/core/src/configuration.ts
ECMAScript/core/src/index.ts
ECMAScript/react/src/hooks/useQuilttConnector.ts

Following on #185, this PR consolidates all Quiltt config in the Core package and allows config variables to be exported.

Export config

---

vite.config.js

This PR adds `**/src/api/graphql/links/actioncable/**` to coverage exclude list

Improve test coverage

---

.changeset/clean-radios-yell.md
examples/react-native-expo/package.json
examples/react-native-expo/yarn.lock
examples/react-nextjs/package.json
package.json
packages/core/package.json
packages/react-native/declarations.d.ts
packages/react-native/package.json
packages/react-native/src/components/QuilttConnector.tsx
packages/react-native/src/utils/connector/checkConnectorUrl.ts
packages/react-native/src/utils/connector/handleOAuthUrl.ts
packages/react/package.json
pnpm-lock.yaml

Revert "React native oauth"

---

pnpm-lock.yaml

Update Example App

---

.changeset/wicked-rocks-shave.md
packages/core/src/api/graphql/client.ts
packages/core/src/api/graphql/links/ActionCableLink.ts
packages/core/src/api/graphql/links/AuthLink.ts
packages/core/src/api/graphql/links/BatchHttpLink.ts
packages/core/src/api/graphql/links/ErrorLink.ts
packages/core/src/api/graphql/links/ForwardableLink.ts
packages/core/src/api/graphql/links/HttpLink.ts
packages/core/src/api/graphql/links/RetryLink.ts
packages/core/src/api/graphql/links/TerminatingLink.ts
packages/core/src/api/graphql/links/VersionLink.ts
packages/react/src/hooks/useQuilttClient.ts
packages/react/src/providers/QuilttAuthProvider.tsx

Fix strict ESM module resolution issues with Apollo client exports

Fix strict imports

---

.changeset/moody-shrimps-roll.md
packages/core/package.json
packages/react-native/package.json
packages/react/package.json

- Added `main` to `package.json` to support analyzing the packages in https://bundlephobia.com

Expose main entry in package.json

---

.changeset/brown-nails-lick.md
packages/react-native/src/components/QuilttConnector.tsx

- [External] Fixed iOS header scroll behavior in WebView preventing unwanted header movement and back button exposure when dragging
- Fixed WebView scroll indicators to provide cleaner UI
- Added overflow control to prevent content from breaking layout boundaries
- Added optimized scroll performance configuration for iOS
- Enhanced WebView content handling with proper styling configuration
- Improved content inset and adjustment behavior for consistent display across screens

[React Native] Bugfix: iOS WebView header drag behavior and scrolling

---

examples/react-native-expo/package.json
examples/react-nextjs/package.json
package.json
packages/core/package.json
packages/react-native/package.json
packages/react/package.json
pnpm-lock.yaml

- Update all affected dependencies for security update

[Security] Update dependencies including Next.js

---

.github/workflows/tests-unit.yml
README.md
package.json
packages/core/package.json
packages/react-native/package.json
packages/react/package.json
turbo.json

- **Breaking** Renamed test commands: `test:coverage` → `test:unit` and `test:cypress` → `test:e2e`
- Added comprehensive testing documentation to README
- Enhanced README with development setup and code quality sections
- Updated GitHub Actions and Turbo config for new test commands
- Streamlined publishing documentation

Update test command and add instructions to README

---

.github/workflows/tests-unit.yml

Re-enable unit tests

---

.changeset/cold-geckos-send.md
.github/workflows/ci.yml
examples/react-native-expo/package.json
examples/react-nextjs/package.json
packages/core/package.json
packages/core/src/api/browser.ts
packages/react-native/package.json
packages/react-native/src/components/QuilttConnector.tsx
packages/react/package.json
packages/react/src/hooks/useQuilttConnector.ts
pnpm-lock.yaml

- Upgrade @rails/actioncable to v8.x.x 
- Add typings for `connectorSession` in `ConnectorSDKCallbackMetadata`

Upgrade @rails/actioncable to v8.x.x

---

packages/react/src/hooks/useQuilttConnector.ts
packages/react/src/providers/QuilttProvider.tsx
packages/react/tests/hooks/useQuilttConnector.test.tsx
packages/react/tests/providers/QuilttAuthProvider.test.tsx

- Update `console.warn` to `console.error` on unexpected component unmount

Update console error when on unexpected component unmount

---

packages/core/CHANGELOG.md
packages/react-native/CHANGELOG.md
packages/react/CHANGELOG.md

Add missing changelog notes
