.changeset/shaggy-glasses-argue.md, ECMAScript/react/src/components/QuilttButton.tsx, ECMAScript/react/src/components/QuilttContainer.tsx, ECMAScript/react/src/types.ts, ECMAScript/react/test-apps/nextjs/app/components/TestCustomButton.cy.tsx, ECMAScript/react/test-apps/nextjs/app/components/TestCustomButton.tsx, ECMAScript/react/test-apps/nextjs/app/components/TestCustomContainer.cy.tsx, ECMAScript/react/test-apps/nextjs/app/components/TestCustomContainer.tsx, ECMAScript/react/test-apps/nextjs/app/components/TestHTMLLauncher.cy.tsx, ECMAScript/react/test-apps/nextjs/app/components/TestHTMLLauncher.tsx, ECMAScript/react/test-apps/nextjs/app/components/index.ts, ECMAScript/react/test-apps/nextjs/app/page.tsx
It's easy to have working code, it's much harder to appease the typescript gods
=> Add support for custom components 'as' props

.changeset/afraid-cobras-chew.md, ECMAScript/core/src/api/rest/AuthAPI.ts, ECMAScript/core/src/api/rest/axios.ts, ECMAScript/react/src/hooks/session/useIdentifySession.ts
I've tested the interceptor using codesandbox.io
=> Add retries to auth api when dealing with network related errors

.changeset/ten-dryers-ring.md, ECMAScript/core/src/api/browser.ts
The `load` event is intended to mirror the behavior of `window.load`, and is different than any `ready` event we may or may not introduce in the future.
> The load event is fired when the whole page has loaded, including all dependent resources such as stylesheets, scripts, iframes, and images. This is in contrast to [DOMContentLoaded](https://developer.mozilla.org/en-US/docs/Web/API/Document/DOMContentLoaded_event), which is fired as soon as the page DOM has been loaded, without waiting for resources to finish loading.
=> SDK Events - Add "Load" EventType

.changeset/brown-onions-carry.md, .changeset/small-shoes-live.md, ECMAScript/core/src/Storage/Local.ts, ECMAScript/core/src/types.ts
Turns out expo has `window` but doesn't have `window.addEventListener`.
So when I import `@quiltt/core` in the react native sdk and use it in an expo app, it just blows up.
```
console.log('window.expo', !!window.expo)
LOG  window.expo true
```
I have a hard time to just use `@quiltt/core` directly in the expo example app, so hoping to add one more check, bump the version so I can use the next `@quiltt/core` directly in the expo example app.
In `node`
```
❯ node
Welcome to Node.js v18.15.0.
Type ".help" for more information.
> typeof window !== 'undefined' && !window?.expo
false
```
In browser
```
typeof window !== 'undefined' && !window?.expo
true
```
In Expo
```
console.log('in expo', typeof window !== 'undefined' && !window?.expo)
LOG  in expo false
```
=> Strict check on browser side code

.changeset/eleven-poets-yawn.md, ECMAScript/react-native/package.json, ECMAScript/react-native/src/components/QuilttConnector.tsx, ECMAScript/react-native/src/index.ts, pnpm-lock.yaml
If I am using `core-js` to polyfill, maybe I don't need `react-native-url-polyfill`.
Plus I think I need core-js in `dependencies` over `devDependencies`.
=> Drop react-native-url-polyfill

.changeset/giant-roses-bow.md, ECMAScript/react-native/package.json
The package wasn't working, I got this error
```
Unable to resolve '@quiltt/react-native' from 'screens/ConnectorScreen.tsx
```
From GH copilot:
```
GitHub Copilot
In your package.json, you should set:
main to point to the CommonJS entry point, which is typically a .js file.
module to point to the ES Modules entry point, which is typically a .mjs file.
types to point to the TypeScript definitions file, which is a .d.ts file.
main points to dist/index.js, which is the entry point for CommonJS modules. This is used by Node.js and tools that don't support ES Modules.
module points to dist/index.mjs, which is the entry point for ES Modules. This is used by modern bundlers like webpack and Rollup.
types points to dist/index.d.ts, which is the TypeScript definitions file. This is used by …
```
=> Fix rn package entrypoint

.changeset/little-jokes-brake.md, ECMAScript/react-native/src/components/QuilttConnector.tsx
It doesn't seems like we need to adjust much for the `profileId` as it should expose into quilttscheme url search params (https://github.com/quiltt/quiltt-public/blob/1f2ee1aa99f39f349ca1c42c627dd83556d03d68/ECMAScript/react-native/src/components/QuilttConnector.tsx#L72). 
But the `MessageType` was changed from `Loaded` to `Load`, so adjusting in this PR, looks right to you? @sirwolfgang
=> react native sdk to match the new MessageType

.changeset/bright-roses-relax.md, ECMAScript/react-native/src/components/QuilttConnector.tsx
Closes: https://github.com/quiltt/quiltt-public/issues/154
Plaid Link is setting bank oauth url directly, seems like there isn't a way to even intercept the url and get the oauth url value in web, so I am treating all non quiltt url as oauth url and launch it thru Safari/ Chrome.
=> Support Plaid oauth in react native sdk

.changeset/shiny-meals-cover.md, ECMAScript/react-native/src/components/QuilttConnector.tsx
Previous logic also launch MX link in mobile Safari/ Chrome which we don't want.
This PR ensure we are only opening bank oauth url in external browser.
=> Fix handle plaid oauth link bug

.github/workflows/check-todos.yml, .github/workflows/ci.yml, .github/workflows/release.yml
Trial the ubuntu runners from BuildJet to see if we can get better performance+pricing on CI runs.
=> Switch quiltt-public CI to use BuildJet Runners

.changeset/honest-donkeys-smell.md, ECMAScript/core/src/JsonWebToken.ts, ECMAScript/core/src/api/rest/AuthAPI.ts
Rename Deployments to Clients in internal auth api. Externally facing interface has been clientId for some time.
=> [Internal] Rename Deployments to Clients in Auth

.changeset/config.json, package.json
This PR upgrades the release flow for the Monorepo.
- Create tags to unblock releases per https://github.com/changesets/action/pull/345
- Improve changelog format
- From this: https://github.com/quiltt/quiltt-public/blob/main/ECMAScript/react/CHANGELOG.md
- To this: https://github.com/changesets/changesets/blob/main/packages/cli/CHANGELOG.md
=> Improve Changelog + Release flow

.changeset/honest-dingos-crash.md, ECMAScript/core/src/api/browser.ts, ECMAScript/react/src/hooks/useQuilttConnector.ts
This exposes the `institution` option for the upcoming version of the Connector API. This allows developers to provide prefilled search terms or selected Institutions.
=> Add Institutions to the Connect API

.changeset/pink-horses-thank.md, packages/react-native/src/components/QuilttConnector.tsx
Plaid for some reason, will attempt to set window.location = about:srcdoc
The way I used to filter it seems to produce a warning
So I just let existing requestHandler, handleQuilttEvent and handleOAuthUrl to handle.
Also remove an unnecessary HB reporting
=> Remove RN about:srcdoc warning

.changeset/clever-boxes-float.md, packages/core/src/storage/Local.ts, packages/core/src/types.ts
This replaces the expo specific check with `typeof` checks that should work in more situations.
=> Improve typeof checks for mobile environments

.changeset/lazy-jokes-chew.md, biome.json, packages/core/src/api/rest/auth.ts, packages/core/src/configuration.ts, packages/core/tests/api/rest/auth.test.ts, packages/core/tests/configuration.test.ts
- Made the package respect `QUILTT_DEBUG=false` env var setting while running CI for apps that use `@quiltt/core`
- Made sure test running config loader handles `undefined` inputs correctly
- Added more configuration test scenarios
=> Fix debugging config

.changeset/hip-beans-train.md, packages/react/README.md, packages/react/src/providers/QuilttAuthProvider.tsx
- Move instantiation of the React GraphQL client into the component to reduce bundle size
- Improve documentation
=> Reduce bundle size

packages/core/README.md, packages/core/package.json, packages/react-native/README.md, packages/react-native/package.json, packages/react/README.md, packages/react/package.json
- Improved documentation
- Updated package.json metadata
=> Improve documentation + OAuth instructions

.changeset/nasty-boxes-sit.md, examples/react-native-expo/package.json, examples/react-nextjs/package.json, package.json, packages/core/package.json, packages/core/src/api/graphql/client.ts, packages/react-native/package.json, packages/react/package.json, packages/react/src/components/QuilttButton.tsx, packages/react/src/components/QuilttContainer.tsx, packages/react/src/types.ts, packages/react/tests/components/QuilttButton.test.tsx, packages/react/tests/components/QuilttContainer.test.tsx, pnpm-lock.yaml
- [External] Improved TypeScript typings for query client and React components
- Updated dependencies:
- `@apollo/client` from `3.11.8` to `3.12.4`
- `bunchee` from `5.6.1` to `6.2.0`
- `typescript` from `5.7.2` to `5.7.3`
- `@types/node` from `22.10.2` to `22.10.5`
- `pnpm` from `9.15.0` to `9.15.3`
- Fixed type definitions in React components by replacing `AnyTag` with `ElementType`
- Improved Apollo Client devtools configuration handling
- Fixed TypeScript compilation issues in GraphQL client implementation
- Fixed type safety in subscription operation checks
=> Improve typings for query client and react components

.changeset/silent-mammals-poke.md, packages/react/src/hooks/useQuilttConnector.ts
- Fixed issue where `Quiltt.reconnect()` was not being called when `connectionId` changed but `connectorId` remained the same
- Removed early return logic that prevented connector recreation
=> Bugfix: early return in effect prevents reconnect from being called
